### ISSUE TITLE
weweChat can not start on Ubuntu 18.10

### ISSUE THREAD

**Issue by 3lackrush** [trazyn/weweChat#213] opened 2019-02-27 02:38 UTC
weweChat can not start on Ubuntu 18.10

**Comment by ukhack** [comment] 2019-03-07 02:13
+1

**Comment by Espylapiza** [comment] 2019-03-28 18:04
[1]    25790 segmentation fault (core dumped)  wewechat

+1

**Comment by zzhiyi** [comment] 2019-04-06 02:28
Duplicate of https://github.com/trazyn/weweChat/issues/196

**Comment by fengye0907** [comment] 2019-06-16 10:13
can't start on Ubuntu 19 as well

**Closed** 2019-06-21 02:56 UTC
