### ISSUE TITLE
fedora29 無法啓動

### ISSUE THREAD

**Issue by svnwell** [trazyn/weweChat#197] opened 2018-11-12 12:23 UTC
Segmentation fault (core dumped)

**Comment by bovver2017** [comment] 2018-11-12 15:55
me too

**Comment by rabbitns** [comment] 2018-11-14 02:32
me too

**Comment by JadeVane** [comment] 2018-11-28 11:57
+1

**Comment by Seven-Steven** [comment] 2018-12-04 03:20
也是这种情况, 克隆仓库自己编译 `run dev` 能正常运行, 编译报错
Ubuntu 18.10

**Comment by DIYcat** [comment] 2018-12-21 03:57
me too

**Comment by JD1412** [comment] 2019-03-07 03:41
me too

**Comment by zzhiyi** [comment] 2019-04-06 02:27
Duplicate of https://github.com/trazyn/weweChat/issues/196

**Comment by svnwell** [comment] 2019-04-26 01:31
源码编译，不再出现此错误

**Closed** 2019-04-26 01:31 UTC
